/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.uni.eurekaapp.view;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import pe.uni.eurekaapp.controller.RepoController;
import pe.uni.eurekaapp.util.Mensaje;
import pe.uni.eurekaapp.util.ReportViewInternal;

/**
 *
 * @author Alumno
 */
public class RepoMovimientosView extends javax.swing.JInternalFrame {

	/**
	 * Creates new form RepoMovimientosView
	 */
	public RepoMovimientosView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    btnEjecutar = new javax.swing.JButton();
    panelRepo = new javax.swing.JPanel();

    setClosable(true);
    setMaximizable(true);
    setTitle("REPORTE DE MOVIMIENTOS");

    jLabel1.setText("Cuenta:");

    btnEjecutar.setBackground(new java.awt.Color(0, 102, 204));
    btnEjecutar.setForeground(new java.awt.Color(255, 255, 255));
    btnEjecutar.setText("Ejecutar");
    btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEjecutarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelRepoLayout = new javax.swing.GroupLayout(panelRepo);
    panelRepo.setLayout(panelRepoLayout);
    panelRepoLayout.setHorizontalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelRepoLayout.setVerticalGroup(
      panelRepoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 313, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(362, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtCuenta)
          .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(panelRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
		try {
			// Cuenta
			String cuenta = txtCuenta.getText();
			// Usando una colección de datos
			RepoController control = new RepoController();
			List<Map<String,?>> lista = control.traerMovimientos(cuenta);
			JRMapCollectionDataSource data = new JRMapCollectionDataSource(lista);
			Map pars = new HashMap();
			String reporte = "/pe/uni/eurekaapp/reports/RepoMovimientos.jrxml";
			InputStream is = FormMain.class.getResourceAsStream(reporte);
			JasperReport rep = JasperCompileManager.compileReport(is);
			JasperPrint print = JasperFillManager.fillReport(rep, pars, data);

			// Visualizando el Reporte
			/*
			JasperViewer viewer = new JasperViewer(print, false);
			viewer.setTitle("Mi Reporte");
			viewer.setVisible(true);
			*/
			
			 // Visualizar el reporte - Caso 2
      ReportViewInternal view = new ReportViewInternal();
      view.setTitle("MOVIMIENTOS");
      view.setReporte(print);
      panelRepo.removeAll();
      panelRepo.add(view);
      view.setVisible(true);
      view.setMaximum(true);
      view.setMaximizable(false);
      view.setIconifiable(false);
      view.setClosed(false);
			//JasperViewer.viewReport(print);
		} catch (Exception ex) {
			Mensaje.showError(rootPane, ex.getMessage());
		}


  }//GEN-LAST:event_btnEjecutarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEjecutar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel panelRepo;
  private javax.swing.JTextField txtCuenta;
  // End of variables declaration//GEN-END:variables
}
