/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionmvc.view;

import aplicacionmvc.controller.CuentaController;
import aplicacionmvc.service.CuentaService;
import aplicacionmvc.util.Mensaje;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author PC FERNANDO
 */
public class ConMovimientosView extends javax.swing.JInternalFrame {

    // Lista de movimientos
    private List<Map<String, ?>> lista = null;
    TablePanel tablePanel = null;
    ArrayList<String> listaCuentas =new ArrayList<String>();
    
    /**
     * Creates new form ConMovimientosView
     */
    public ConMovimientosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        tab_principal = new javax.swing.JTabbedPane();

        setTitle("MOVIMIENTOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTROL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Cuenta:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmvc/img/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmvc/img/excel.png"))); // NOI18N
        btnExcel.setEnabled(false);

        btnCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmvc/img/editar.png"))); // NOI18N
        btnCSV.setEnabled(false);
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmvc/img/pdf.png"))); // NOI18N
        btnPDF.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_principal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(51, 102, 255))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab_principal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCSVActionPerformed

    public void registrarCuenta(String cuenta){
        System.out.println(listaCuentas);
        listaCuentas.add(cuenta);
        System.out.println(listaCuentas);
    }
    public boolean cuentaIngresada(String cuenta) {
        
        boolean yaEsta=false;
        
        for (int i = 0; i <= listaCuentas.size() - 1; i++) {
            if (listaCuentas.get(i).equals(cuenta)) {
                yaEsta = true;
                break;
            }

        }
        return yaEsta;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        // Previo
        btnBuscar.setEnabled(false);
        btnExcel.setEnabled(false);
        btnCSV.setEnabled(false);
        btnPDF.setEnabled(false);

        // Proceso
        try {
            // Datos
            String cuenta = txtCuenta.getText();
            registrarCuenta(cuenta);
            boolean seEncuentra=cuentaIngresada(cuenta);
            
            
            // La consulta
            CuentaController control = new CuentaController();
            lista = control.traerMovimientos(cuenta);
            listaCuentas = new ArrayList<String>();
            
            // Reporte
            CuentaService cs = new CuentaService();
            tablePanel = new TablePanel();

            
            
            if (!listaCuentas.isEmpty()) {

                if (!seEncuentra && cs.afirmaCuenta(cuenta) && cuenta.length() == 8) {

                    tablePanel.ActualizaTabla(lista);
                    tab_principal.addTab(cuenta, tablePanel);
                    tab_principal.setSelectedComponent(tablePanel);

                }
                if (seEncuentra) {
                    tab_principal.setSelectedComponent(tablePanel);

                }

            } else {

                if (cs.afirmaCuenta(cuenta) && cuenta.length() == 8) {

                    tablePanel.ActualizaTabla(lista);
                    tab_principal.addTab(cuenta, tablePanel);
                    tab_principal.setSelectedComponent(tablePanel);

                }
            }
            
            
            
            /*DefaultTableModel tabla;
            tabla = (DefaultTableModel) tblRepo.getModel();
            tabla.setRowCount(0);
            for (Map<String, ?> map : lista) {
                Object[] rowData = {
                    map.get("CUENTA"),
                    map.get("MOVIMIENTO"),
                    map.get("FECHA"),
                    map.get("TIPO"),
                    map.get("IMPORTE")
                };
                tabla.addRow(rowData);
            }*/
        } catch (Exception e) {
            Mensaje.showError(rootPane, e.getMessage());
        } finally {
            btnBuscar.setEnabled(true);
            if (lista != null && lista.size() > 0) {
                btnExcel.setEnabled(true);
                btnCSV.setEnabled(true);
                btnPDF.setEnabled(true);
            }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
