/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.uni.eurekaapp.view;

import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import pe.uni.eurekaapp.db.AccesoDB;
import pe.uni.eurekaapp.model.EmpleadoModel;
import pe.uni.eurekaapp.util.Mensaje;
import pe.uni.eurekaapp.util.Session;

/**
 *
 * @author Alumno
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        //Maximizar el formulario
        this.setExtendedState(MAXIMIZED_BOTH);
        
        //Titulo
        establecerTitulo();
    }

    private void establecerTitulo() {
        String titulo = "EUREKA APP";
        EmpleadoModel model;
        model = (EmpleadoModel) Session.get("USUARIO");
        titulo += " (Usuario:" + model.getUsuario() + ")";
        this.setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuProceso = new javax.swing.JMenu();
        menuProcesoDeposito = new javax.swing.JMenuItem();
        menuProcesoRetiro = new javax.swing.JMenuItem();
        menuTabla = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuConsultaMovimientos = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenu();
        btnRepoCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setMnemonic('f');
        menuArchivo.setText("Archivo");

        menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/uni/eurekaapp/img/exit.png"))); // NOI18N
        menuArchivoSalir.setMnemonic('o');
        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        menuBar.add(menuArchivo);

        menuProceso.setMnemonic('e');
        menuProceso.setText("Proceso");

        menuProcesoDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/uni/eurekaapp/img/bag_black.png"))); // NOI18N
        menuProcesoDeposito.setText("Deposito");
        menuProcesoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoDepositoActionPerformed(evt);
            }
        });
        menuProceso.add(menuProcesoDeposito);

        menuProcesoRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/uni/eurekaapp/img/US-dollar.png"))); // NOI18N
        menuProcesoRetiro.setText("Retiro");
        menuProcesoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoRetiroActionPerformed(evt);
            }
        });
        menuProceso.add(menuProcesoRetiro);

        menuBar.add(menuProceso);

        menuTabla.setMnemonic('h');
        menuTabla.setText("Tabla");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        menuTabla.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        menuTabla.add(aboutMenuItem);

        menuBar.add(menuTabla);

        menuConsulta.setText("Consulta");

        menuConsultaMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/uni/eurekaapp/img/13.png"))); // NOI18N
        menuConsultaMovimientos.setText("Movimientos");
        menuConsultaMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaMovimientosActionPerformed(evt);
            }
        });
        menuConsulta.add(menuConsultaMovimientos);

        menuBar.add(menuConsulta);

        menuReporte.setText("Reporte");

        btnRepoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/uni/eurekaapp/img/libro_azul.png"))); // NOI18N
        btnRepoCliente.setText("Clientes");
        btnRepoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepoClienteActionPerformed(evt);
            }
        });
        menuReporte.add(btnRepoCliente);

        menuBar.add(menuReporte);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuArchivoSalirActionPerformed

    private void menuConsultaMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaMovimientosActionPerformed
        cargarFormulario(ConMovimientosView.class);
    }//GEN-LAST:event_menuConsultaMovimientosActionPerformed

    private void menuProcesoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoRetiroActionPerformed
        // TODO add your handling code here:
        cargarFormulario(ProcRetiroView.class);
    }//GEN-LAST:event_menuProcesoRetiroActionPerformed

    private void menuProcesoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoDepositoActionPerformed
        // TODO add your handling code here:
        cargarFormulario(ProcDepositoView.class);
    }//GEN-LAST:event_menuProcesoDepositoActionPerformed

    private void btnRepoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepoClienteActionPerformed
        // TODO add your handling code here:
        Connection cn = null;
        try {
          // El objeto Connection
          cn = AccesoDB.getConnection();
          // Parámetros
          // Cargar el logo
          String fileLogo = "/pe/uni/eurekaapp/img/logo.gif";
          InputStream isLogo = Class.class.getResourceAsStream(fileLogo);     
          Map<String,Object> pars = new HashMap<>();
          pars.put("LOGO", isLogo);
          // Cargando el archivo compilado
          String fileRepo = "/pe/uni/eurekaapp/report/repoClientes.jasper";
          InputStream isRepo = Class.class.getResourceAsStream(fileRepo);
          JasperReport jrRepo = (JasperReport) JRLoader.loadObject(isRepo);
          JasperPrint jpRepo = JasperFillManager.fillReport(jrRepo, pars, cn);

          // Visualizando el Reporte
          JasperViewer viewer = new JasperViewer(jpRepo, false);
          viewer.setTitle("REPORTE DE CLIENTES");
          viewer.setVisible(true);

        } catch (Exception e) {
            Mensaje.showError(rootPane, e.getMessage());
        } finally{
          try {
            cn.close();
          } catch (Exception e) {
          }
        }
    }//GEN-LAST:event_btnRepoClienteActionPerformed

    /**     
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem btnRepoCliente;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuConsultaMovimientos;
    private javax.swing.JMenu menuProceso;
    private javax.swing.JMenuItem menuProcesoDeposito;
    private javax.swing.JMenuItem menuProcesoRetiro;
    private javax.swing.JMenu menuReporte;
    private javax.swing.JMenu menuTabla;
    // End of variables declaration//GEN-END:variables

    private void cargarFormulario(Class<?> aClass) {
        try {
            // Buscar una instancia
            JInternalFrame view = null;
            for (JInternalFrame frame : desktopPane.getAllFrames()) {
                if (aClass.isInstance(frame)) {
                    view = frame;
                    break;
                }
            }
            // Crear la instancia
            if (view == null) {
                view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
                desktopPane.add(view);
            }
            // Hacerlo visible
            view.setVisible(true);
            view.setSelected(true);
            //view.setMaximum(true);
        } catch (Exception e) {

        }
    }
    
}
