
create or replace procedure eureka.cliente_ins (
    p_CHR_CLIECODIGO in CLIENTE.CHR_CLIECODIGO%type
    ,p_VCH_CLIENOMBRE in CLIENTE.VCH_CLIENOMBRE%type
    ,p_VCH_CLIEPATERNO in CLIENTE.VCH_CLIEPATERNO%type
    ,p_VCH_CLIEMATERNO in CLIENTE.VCH_CLIEMATERNO%type
    ,p_CHR_CLIEDNI in CLIENTE.CHR_CLIEDNI%type
    ,p_VCH_CLIEDIRECCION in CLIENTE.VCH_CLIEDIRECCION%type
    ,p_VCH_CLIECIUDAD in CLIENTE.VCH_CLIECIUDAD%type
    ,p_VCH_CLIEEMAIL in CLIENTE.VCH_CLIEEMAIL%type default null 
    ,p_VCH_CLIETELEFONO in CLIENTE.VCH_CLIETELEFONO%type default null 
) 
is
begin
    insert into CLIENTE(
    CHR_CLIECODIGO
    ,VCH_CLIENOMBRE
    ,VCH_CLIEPATERNO
    ,VCH_CLIEMATERNO
    ,CHR_CLIEDNI
    ,VCH_CLIEDIRECCION
    ,VCH_CLIECIUDAD
    ,VCH_CLIEEMAIL
    ,VCH_CLIETELEFONO
    ) values (
    p_CHR_CLIECODIGO
    ,p_VCH_CLIENOMBRE
    ,p_VCH_CLIEPATERNO
    ,p_VCH_CLIEMATERNO
    ,p_CHR_CLIEDNI
    ,p_VCH_CLIEDIRECCION
    ,p_VCH_CLIECIUDAD
    ,p_VCH_CLIEEMAIL
    ,p_VCH_CLIETELEFONO
    );
    commit;
end;
/





